/**
 * This file is @generated by fetch_schema.py
 * Do not edit manually.
 */

export const collections = {
	users: {
		id: '_pb_users_auth_',
		listRule: '@request.auth.id != ""',
		viewRule: '@request.auth.id != ""',
		createRule: '',
		updateRule: 'id = @request.auth.id',
		deleteRule: '@request.auth.id != ""',
		name: 'users',
		type: 'auth',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				cost: 0,
				hidden: true,
				id: 'password901924565',
				max: 0,
				min: 8,
				name: 'password',
				pattern: '',
				presentable: false,
				required: true,
				system: true,
				type: 'password'
			},
			{
				autogeneratePattern: '[a-zA-Z0-9]{50}',
				hidden: true,
				id: 'text2504183744',
				max: 60,
				min: 30,
				name: 'tokenKey',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: true,
				type: 'text'
			},
			{
				exceptDomains: null,
				hidden: false,
				id: 'email3885137012',
				name: 'email',
				onlyDomains: null,
				presentable: false,
				required: true,
				system: true,
				type: 'email'
			},
			{
				hidden: false,
				id: 'bool1547992806',
				name: 'emailVisibility',
				presentable: false,
				required: false,
				system: true,
				type: 'bool'
			},
			{
				hidden: false,
				id: 'bool256245529',
				name: 'verified',
				presentable: false,
				required: false,
				system: true,
				type: 'bool'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1579384326',
				max: 255,
				min: 0,
				name: 'name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				hidden: false,
				id: 'file376926767',
				maxSelect: 1,
				maxSize: 0,
				mimeTypes: ['image/jpeg', 'image/png', 'image/svg+xml', 'image/gif', 'image/webp'],
				name: 'avatar',
				presentable: false,
				protected: false,
				required: false,
				system: false,
				thumbs: null,
				type: 'file'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [
			'CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)',
			"CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''"
		],
		created: '2026-01-21 19:28:38.679Z',
		updated: '2026-01-29 12:10:33.439Z',
		system: false,
		authRule: '',
		manageRule: null,
		authAlert: {
			enabled: true,
			emailTemplate: {
				subject: 'Login from a new location',
				body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
			}
		},
		oauth2: {
			providers: [],
			mappedFields: {
				id: '',
				name: 'name',
				username: '',
				avatarURL: 'avatar'
			},
			enabled: false
		},
		passwordAuth: {
			enabled: true,
			identityFields: ['email']
		},
		mfa: {
			enabled: false,
			duration: 1800,
			rule: ''
		},
		otp: {
			enabled: false,
			duration: 180,
			length: 8,
			emailTemplate: {
				subject: 'OTP for {APP_NAME}',
				body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
			}
		},
		authToken: {
			duration: 604800
		},
		passwordResetToken: {
			duration: 1800
		},
		emailChangeToken: {
			duration: 1800
		},
		verificationToken: {
			duration: 259200
		},
		fileToken: {
			duration: 180
		},
		verificationTemplate: {
			subject: 'Verify your {APP_NAME} email',
			body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>'
		},
		resetPasswordTemplate: {
			subject: 'Reset your {APP_NAME} password',
			body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>'
		},
		confirmEmailChangeTemplate: {
			subject: 'Confirm your {APP_NAME} new email address',
			body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>'
		}
	},
	students: {
		id: 'pbc_3827815851',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: '@request.auth.id != ""',
		name: 'students',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1843675174',
				max: 0,
				min: 0,
				name: 'description',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_2970041692',
				hidden: false,
				id: 'relation2465036164',
				maxSelect: 1,
				minSelect: 0,
				name: 'program',
				presentable: false,
				required: true,
				system: false,
				type: 'relation'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_1749964444',
				hidden: false,
				id: 'relation3145888567',
				maxSelect: 1,
				minSelect: 0,
				name: 'year',
				presentable: false,
				required: true,
				system: false,
				type: 'relation'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text2849095986',
				max: 0,
				min: 0,
				name: 'first_name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: false,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text3356015194',
				max: 0,
				min: 0,
				name: 'last_name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: false,
				type: 'text'
			},
			{
				hidden: false,
				id: 'bool255841855',
				name: 'scholarship',
				presentable: false,
				required: false,
				system: false,
				type: 'bool'
			},
			{
				hidden: false,
				id: 'json1755560041',
				maxSize: 0,
				name: 'socials',
				presentable: false,
				required: false,
				system: false,
				type: 'json'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: ['CREATE INDEX `idx_iQu2ruXpzj` ON `students` (`year`)'],
		created: '2026-01-21 19:32:57.993Z',
		updated: '2026-01-27 14:50:43.314Z',
		system: false
	},
	projects: {
		id: 'pbc_484305853',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: '@request.auth.id != ""',
		name: 'projects',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1579384326',
				max: 0,
				min: 0,
				name: 'name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: false,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1843675174',
				max: 0,
				min: 0,
				name: 'description',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_3827815851',
				hidden: false,
				id: 'relation3072569139',
				maxSelect: 999,
				minSelect: 0,
				name: 'students',
				presentable: false,
				required: true,
				system: false,
				type: 'relation'
			},
			{
				hidden: false,
				id: 'file104153177',
				maxSelect: 99,
				maxSize: 0,
				mimeTypes: [],
				name: 'files',
				presentable: false,
				protected: false,
				required: false,
				system: false,
				thumbs: [],
				type: 'file'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_28645432',
				hidden: false,
				id: 'relation59357059',
				maxSelect: 999,
				minSelect: 0,
				name: 'tags',
				presentable: false,
				required: false,
				system: false,
				type: 'relation'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_1749964444',
				hidden: false,
				id: 'relation3145888567',
				maxSelect: 1,
				minSelect: 0,
				name: 'year',
				presentable: false,
				required: true,
				system: false,
				type: 'relation'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: ['CREATE INDEX `idx_3vmsGn6esC` ON `projects` (`year`)'],
		created: '2026-01-21 19:33:02.926Z',
		updated: '2026-01-27 14:27:34.397Z',
		system: false
	},
	globals: {
		id: 'pbc_4261701616',
		listRule: null,
		viewRule: null,
		createRule: null,
		updateRule: null,
		deleteRule: null,
		name: 'globals',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-21 19:34:49.076Z',
		updated: '2026-01-21 19:34:49.076Z',
		system: false
	},
	years: {
		id: 'pbc_1749964444',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: null,
		name: 'years',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text3208210256',
				max: 4,
				min: 4,
				name: 'id',
				pattern: '^[0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				hidden: false,
				id: 'bool1182570132',
				name: 'draft',
				presentable: false,
				required: false,
				system: false,
				type: 'bool'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-21 19:35:18.950Z',
		updated: '2026-01-29 11:32:13.202Z',
		system: false
	},
	programs: {
		id: 'pbc_2970041692',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: '@request.auth.id != ""',
		name: 'programs',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1579384326',
				max: 0,
				min: 0,
				name: 'name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: false,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1843675174',
				max: 0,
				min: 0,
				name: 'description',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				hidden: false,
				id: 'json1542800728',
				maxSize: 0,
				name: 'metadata',
				presentable: false,
				required: false,
				system: false,
				type: 'json'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-21 19:38:28.606Z',
		updated: '2026-01-26 12:51:30.694Z',
		system: false
	},
	project_tags: {
		id: 'pbc_28645432',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: '@request.auth.id != ""',
		name: 'project_tags',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1579384326',
				max: 0,
				min: 0,
				name: 'name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: false,
				type: 'text'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-21 21:09:17.856Z',
		updated: '2026-01-25 17:05:45.529Z',
		system: false
	},
	socials: {
		id: 'pbc_4193306499',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: '@request.auth.id != ""',
		name: 'socials',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1579384326',
				max: 0,
				min: 0,
				name: 'name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				exceptDomains: null,
				hidden: false,
				id: 'url4101391790',
				name: 'url',
				onlyDomains: null,
				presentable: false,
				required: false,
				system: false,
				type: 'url'
			},
			{
				hidden: false,
				id: 'number1169138922',
				max: null,
				min: null,
				name: 'sort_order',
				onlyInt: false,
				presentable: false,
				required: false,
				system: false,
				type: 'number'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-24 17:21:12.132Z',
		updated: '2026-01-29 12:22:15.354Z',
		system: false
	},
	student_drafts: {
		id: 'pbc_951725104',
		listRule: '',
		viewRule: '',
		createRule: '',
		updateRule: '',
		deleteRule: '@request.auth.id != ""',
		name: 'student_drafts',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1843675174',
				max: 0,
				min: 0,
				name: 'description',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				hidden: false,
				id: 'json1755560041',
				maxSize: 0,
				name: 'socials',
				presentable: false,
				required: false,
				system: false,
				type: 'json'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-27 14:26:33.993Z',
		updated: '2026-01-27 15:59:23.963Z',
		system: false
	},
	project_drafts: {
		id: 'pbc_3697637917',
		listRule: '',
		viewRule: '',
		createRule: '@request.auth.id != ""',
		updateRule: '@request.auth.id != ""',
		deleteRule: '@request.auth.id != ""',
		name: 'project_drafts',
		type: 'base',
		fields: [
			{
				autogeneratePattern: '[a-z0-9]{15}',
				hidden: false,
				id: 'text3208210256',
				max: 15,
				min: 15,
				name: 'id',
				pattern: '^[a-z0-9]+$',
				presentable: false,
				primaryKey: true,
				required: true,
				system: true,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1579384326',
				max: 0,
				min: 0,
				name: 'name',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: true,
				system: false,
				type: 'text'
			},
			{
				autogeneratePattern: '',
				hidden: false,
				id: 'text1843675174',
				max: 0,
				min: 0,
				name: 'description',
				pattern: '',
				presentable: false,
				primaryKey: false,
				required: false,
				system: false,
				type: 'text'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_3827815851',
				hidden: false,
				id: 'relation2758380978',
				maxSelect: 999,
				minSelect: 0,
				name: 'students',
				presentable: false,
				required: true,
				system: false,
				type: 'relation'
			},
			{
				hidden: false,
				id: 'file104153177',
				maxSelect: 99,
				maxSize: 0,
				mimeTypes: [],
				name: 'files',
				presentable: false,
				protected: false,
				required: false,
				system: false,
				thumbs: [],
				type: 'file'
			},
			{
				cascadeDelete: false,
				collectionId: 'pbc_28645432',
				hidden: false,
				id: 'relation1874629670',
				maxSelect: 999,
				minSelect: 0,
				name: 'tags',
				presentable: false,
				required: false,
				system: false,
				type: 'relation'
			},
			{
				hidden: false,
				id: 'autodate2990389176',
				name: 'created',
				onCreate: true,
				onUpdate: false,
				presentable: false,
				system: false,
				type: 'autodate'
			},
			{
				hidden: false,
				id: 'autodate3332085495',
				name: 'updated',
				onCreate: true,
				onUpdate: true,
				presentable: false,
				system: false,
				type: 'autodate'
			}
		],
		indexes: [],
		created: '2026-01-27 14:28:48.052Z',
		updated: '2026-01-27 14:28:48.052Z',
		system: false
	}
} as const;

export type PbSchema = typeof collections;
